# Where you want to keep your music files for mpd to watch
music_directory		"~/Music"

# Where you want to keep your playlist files for mpd to save and load
playlist_directory		"~/Music/playlists"

# Where you want the mpd database file to be stored
db_file			"~/Music/database"

# The address to run mpd from (in this case localhost)
bind_to_address		"127.0.0.1"

# Enables mpd to watch the above "music_directory" to automatically update
# If not enabled, you'd need to make sure to update via your client (rmpc)
auto_update	"yes"

# This is one of the few parameters set by default in the example config
input {
        plugin "curl"
#       proxy "proxy.isp.com:8080"
#       proxy_user "user"
#       proxy_password "password"
}

# Here you'd need to make sure you use YOUR audio server.
# To do so, run `inxi -A` and check.
audio_output {
	type		"pipewire"
	name		"PipeWire Sound Server"
}

audio_output {
    type   "fifo"
    name   "my_fifo"
    path   "/tmp/mpd.fifo"
    format "44100:16:2"
}

